### ISSUE TITLE
installing console-telemetry-plugin on OpenShift version 4.8.13 causing console errors

### ISSUE THREAD

**Issue by redhatHameed** [christianvogt/console-telemetry-plugin#1]
I have set up console telemetry plugin on OpenShift version 4.8.13 causing console errors while navigating different pages/menus and causing below seen errors, note after refreshing the page it went, but comes again if navigates to another page/menu

<img width="1354" alt="Screen Shot 2021-10-16 at 2 22 35 PM" src="https://user-images.githubusercontent.com/41960152/137598280-0486c5af-ddf6-4787-818c-d9df0a67d2c7.png">

<img width="810" alt="Screen Shot 2021-10-16 at 2 23 03 PM" src="https://user-images.githubusercontent.com/41960152/137598279-273796d1-67b3-494b-be44-2dd199d0e04e.png">

this error did not happen on openshift version 4.8.12

**Comment by christianvogt** [comment]
@redhatHameed the logs show that the telemetry plugin is receiving the events and logging to console correctly (no segment key has been setup).

The error `t is not a function` is from the react-i18next localization function which is unrelated to the telemetry plugin.

Can you confirm whether the error still occurs even when the plugin is uninstalled / disabled?

**Comment by redhatHameed** [comment]
@christianvogt thanks for your quick reply, so if I disabled the telemetry plugin, I am not getting the error. 

disabling the plugin -> 
https://user-images.githubusercontent.com/41960152/137653364-7caaf987-c072-45a7-934d-111443b9a6fe.mov


enabling the plugin ->
https://user-images.githubusercontent.com/41960152/137654530-297c6fd8-33f0-465b-8ee5-9d56149eedf2.mov

**Comment by christianvogt** [comment]
@redhatHameed thank you for the update and showing the video of when the error occurs. I'll look into it.

**Comment by yzhao583** [comment]
@christianvogt @redhatHameed Found something new, but not sure is it related to this issue.
![image](https://user-images.githubusercontent.com/24922241/137808464-60c52cc7-d2d8-4d81-823e-67880ed618a5.png)

**Comment by christianvogt** [comment]
@yzhao583 what's interesting here is that the error you display indicates that the telemetry listener from the plugin has failed to load. Whereas the screenshots in the description show a console log where the telemetry event listener is receiving events.

Is there a cluster you can share with me to debug? (feel free to ping me on slack)

**Comment by yzhao583** [comment]
@christianvogt Thank you for your response, here is a cluster you can use, please kindly note that it is using OCP 4.8.14, but we still can reproduce the issue, your help is much appreciated.

Link for the cluster:  [https://console-openshift-console.apps.rhoda-ocp4814.kni.syseng.devcluster.openshift.com/dashboards](https://console-openshift-console.apps.rhoda-ocp4814.kni.syseng.devcluster.openshift.com/dashboards)

I will ping you on slack for credentials.

**Comment by christianvogt** [comment]
After further investigation, the error is not with the telemetry plugin but with a knative extension and the failure to resolve a function.
Closing in lieu of the following bug for the console:
https://bugzilla.redhat.com/show_bug.cgi?id=2017130
